# Generated by Django 2.2.4 on 2021-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
